name: clerk_auth
description: Package that will allow you to authenticate and use Clerk from Dart code.
version: 0.0.7-dev
homepage: https://clerk.com/docs
repository: https://github.com/clerk/clerk-sdk-flutter/tree/main/packages/clerk_auth
issue_tracker: https://github.com/clerk/clerk-sdk-flutter/labels/clerk_auth
topics:
  - authentication

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  http: ^1.1.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  meta: ">=1.9.1 <2.0.0"

dev_dependencies:
  build_runner: any
  build_version: ^2.1.1
  dart_dotenv: ^1.0.1
  json_serializable: ^6.8.0
  lints: ^3.0.0
  mocktail: ^1.0.4
  test: ^1.25.5
  uuid: ^4.5.1
