name: clerk_sdk
version: 0.0.9-beta
description: >
  Clerk SDK containing all packages that define use of Clerk 
  services for Dart and Flutter code.
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dev_dependencies:
  melos: ^6.1.0
