name: clerk_flutter_example
description: Example application for linking to clerk_flutter
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.6.2 <4.0.0'
  flutter: '>=3.27.4'

dependencies:
  flutter:
    sdk: flutter
  clerk_flutter: '>=0.0.12-beta'
  clerk_auth: '>=0.0.12-beta'
  app_links: ^3.5.1
  url_launcher_ios: 6.2.0
  google_sign_in: ^7.1.0
  uuid: ^4.5.1
  win32: ^5.5.4

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
