name: test_support
description: This package is used indirectly by the test suite of clerk_auth using symlinks
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.6.2 <4.0.0'

dependencies:
  http: ^1.1.0
  clerk_auth:
    path: ../packages/clerk_auth

dev_dependencies:
  dart_dotenv: ^1.0.1
  lints: ^3.0.0
  test: ^1.25.5
